
services:

  webserver:
    image: nginx:alpine
    container_name: ${APP}-webserver
    working_dir: /mnt/api
    volumes:
      - ./api:/mnt/api
      - ./app:/mnt/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
      - "8081:8081"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: ${APP}-php-fpm
    working_dir: /mnt/api/
    volumes:
      - ./api:/mnt/api/
      - .env:/mnt/api/.env
      - ./docker/php-fpm/php-ini-overrides.local.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
    ports:
      - "8000:8000"

  database:
    image: mysql:8.0.32
    container_name: ${APP}-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./data/volumes/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${APP}-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq/log/:/var/log/rabbitmq
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia

  redis:
    image: redis:alpine
    container_name: ${APP}-redis

  adminredis:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_NAME=MyRedis
    ports:
      - "8092:80"
